version: '3.8'

services:
  app:
    build: .
    ports:
      - '${PORT:-5002}:${PORT:-5002}'
    volumes:
      - ./src:/app/src
      - ./build:/app/build
      - ./node_modules:/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    restart: unless-stopped
